In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
data={
    'company':['google','google','google','google','google','google','abc pharma','abc pharma','abc pharma','abc pharma','facebook','facebook','facebook','facebook','facebook','facebook'],
    'job':['sales executive','sales executive','business manager','business manager','computer programmer','computer programmer','sales executive','computer programmer','business manager','business manager','sales executive','sales executive','business manager','business manager','computer programmer','computer programmer'],
    'degree':['bachelors','masters','bachelors','masters','bachelors','masters','masters','bachelors','bachelors','masters','bachelors','masters','bachelors','masters','bachelors','masters'],
    'salary_more_than_100k':[0,0,1,1,0,1,0,0,0,1,1,1,1,1,1,1]
}

In [6]:
df=pd.DataFrame(data)
print(df)

       company                  job     degree  salary_more_than_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [21]:
inputs=df.drop('salary_more_than_100k',axis=1)
target=df['salary_more_than_100k']

In [18]:
inputs

       company                  job     degree  company_n  job_n   degree_n
0       google      sales executive  bachelors          2       2         2
1       google      sales executive    masters          2       2         2
2       google     business manager  bachelors          2       2         2
3       google     business manager    masters          2       2         2
4       google  computer programmer  bachelors          2       2         2
5       google  computer programmer    masters          2       2         2
6   abc pharma      sales executive    masters          0       0         0
7   abc pharma  computer programmer  bachelors          0       0         0
8   abc pharma     business manager  bachelors          0       0         0
9   abc pharma     business manager    masters          0       0         0
10    facebook      sales executive  bachelors          1       1         1
11    facebook      sales executive    masters          1       1         1
12    facebook     business manager  bachelors          1       1         1
13    facebook     business manager    masters          1       1         1
14    facebook  computer programmer  bachelors          1       1         1
15    facebook  computer programmer    masters          1       1         1

In [10]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_than_100k, dtype: int64

In [20]:
from sklearn.preprocessing import LabelEncoder
le_company=LabelEncoder()
le_job=LabelEncoder()
le_degree=LabelEncoder()

In [26]:
inputs['company_n']=le_company.fit_transform(inputs['company'])
inputs['job_n ']=le_job.fit_transform(inputs['job'])
inputs['degree_n']=le_degree.fit_transform(inputs['degree'])
inputs

       company                  job     degree  company_n  job_n   degree_n
0       google      sales executive  bachelors          2       2         0
1       google      sales executive    masters          2       2         1
2       google     business manager  bachelors          2       0         0
3       google     business manager    masters          2       0         1
4       google  computer programmer  bachelors          2       1         0
5       google  computer programmer    masters          2       1         1
6   abc pharma      sales executive    masters          0       2         1
7   abc pharma  computer programmer  bachelors          0       1         0
8   abc pharma     business manager  bachelors          0       0         0
9   abc pharma     business manager    masters          0       0         1
10    facebook      sales executive  bachelors          1       2         0
11    facebook      sales executive    masters          1       2         1
12    facebook     business manager  bachelors          1       0         0
13    facebook     business manager    masters          1       0         1
14    facebook  computer programmer  bachelors          1       1         0
15    facebook  computer programmer    masters          1       1         1

In [27]:
inputs_n=inputs.drop(['company','job','degree'],axis='columns')
inputs_n

    company_n  job_n   degree_n
0           2       2         0
1           2       2         1
2           2       0         0
3           2       0         1
4           2       1         0
5           2       1         1
6           0       2         1
7           0       1         0
8           0       0         0
9           0       0         1
10          1       2         0
11          1       2         1
12          1       0         0
13          1       0         1
14          1       1         0
15          1       1         1

In [28]:
from sklearn import tree

In [29]:
model=tree.DecisionTreeClassifier()

In [30]:
model.fit(inputs_n,target)

DecisionTreeClassifier()

In [31]:
model.score(inputs_n,target)

1.0

In [33]:
model.predict([[2,2,1]])

/Users/kpvarma/PycharmProjects/MachineLearning/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [34]:
model.predict([[2,0,1]])

/Users/kpvarma/PycharmProjects/MachineLearning/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])