In [18]:
import pandas as pd
import numpy as np
data={
    'name':['Braund,Owen','Cuming,john','Heikken,laina','Futrelle,Jacques','Allen,William','Moranm,james','Mccarthy,timotty','palsson,Gosta','johnson,oscar','Nasser,Nicholas'],
    'pclass':[3,1,3,1,3,3,1,3,3,2],
    'sex':['male','female','female','female','male','male','male','male','female','female'],
    'age':[22,38,26,35,35,np.nan,54,2,27,14],
    'sibsp':[1,1,0,1,0,0,0,3,0,1],
    'parch':[0,0,0,0,0,0,0,1,2,0],
    'ticket':[21171,17599,3101282,113803,373450,330877,17463,349909,347742,237736],
    'fare':[7.25,71.2833,7.925,53.1,8.05,8.4583,51.8625,21.075,11.1333,30.0708],
    'cabin':[np.nan,'c85',np.nan,'c123',np.nan,np.nan,'e46',np.nan,np.nan,np.nan],
    'embarked':['s','c','s','s','s','q','s','s','s','c'],
    'survived':[0,1,1,1,0,0,0,0,1,1]
}

In [25]:
df=pd.DataFrame(data)
df

,name,pclass,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,"Braund,Owen",3,male,22.0,1,0,21171,7.2500,NaN,s,0
1,"Cuming,john",1,female,38.0,1,0,17599,71.2833,c85,c,1
2,"Heikken,laina",3,female,26.0,0,0,3101282,7.9250,NaN,s,1
3,"Futrelle,Jacques",1,female,35.0,1,0,113803,53.1000,c123,s,1
4,"Allen,William",3,male,35.0,0,0,373450,8.0500,NaN,s,0
5,"Moranm,james",3,male,NaN,0,0,330877,8.4583,NaN,q,0
6,"Mccarthy,timotty",1,male,54.0,0,0,17463,51.8625,e46,s,0
7,"palsson,Gosta",3,male,2.0,3,1,349909,21.0750,NaN,s,0
8,"johnson,oscar",3,female,27.0,0,2,347742,11.1333,NaN,s,1
9,"Nasser,Nicholas",2,female,14.0,1,0,237736,30.0708,NaN,c,1

In [50]:
df.drop(['name','sibsp','parch','ticket','cabin','embarked'],axis='columns',inplace=True)
df

KeyError: "['name', 'sibsp', 'parch', 'ticket', 'cabin', 'embarked'] not found in axis"

In [49]:
target=df.survived
input=df.drop('survived',axis='columns')

In [31]:
dummies=pd.get_dummies(input.sex).astype(int)
dummies

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1
5       0     1
6       0     1
7       0     1
8       1     0
9       1     0

In [37]:
inputs=pd.concat([input,dummies],axis='columns')
inputs

   pclass     sex   age     fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1
5       3    male   NaN   8.4583       0     1
6       1    male  54.0  51.8625       0     1
7       3    male   2.0  21.0750       0     1
8       3  female  27.0  11.1333       1     0
9       2  female  14.0  30.0708       1     0

In [40]:
inputs.drop('sex',axis='columns',inplace=True)
inputs

   pclass   age     fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1
5       3   NaN   8.4583       0     1
6       1  54.0  51.8625       0     1
7       3   2.0  21.0750       0     1
8       3  27.0  11.1333       1     0
9       2  14.0  30.0708       1     0

In [41]:
inputs.age=inputs.age.fillna(inputs.age.mean())
inputs.head()

   pclass   age     fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [42]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(inputs,target,test_size=0.3)

In [53]:
len(x_train)

7

In [54]:
from sklearn.naive_bayes import GaussianNB
model= GaussianNB()

In [55]:
model.fit(x_train,y_train)

GaussianNB()

In [56]:
model.score(x_test,y_test)

0.6666666666666666

In [57]:
x_test[:5]

   pclass   age     fare  female  male
7       3   2.0  21.0750       0     1
4       3  35.0   8.0500       0     1
6       1  54.0  51.8625       0     1

In [58]:
y_test

7    0
4    0
6    0
Name: survived, dtype: int64

In [59]:
model.predict(x_test)

array([0, 0, 1])